### ISSUE TITLE
epoch超长时间是为什么呢？

### ISSUE THREAD

**Issue by tan-yishu** [hemingkx/ChineseNMT#4]
![image](https://user-images.githubusercontent.com/80763002/116524590-232f4680-a90a-11eb-9566-88f51c6b52c0.png)
2GPU，8CPU。。一个epoch要一个多小时。。555

**Comment by hemingkx** [comment]
训练时间在readme和知乎文章中已经说明了哦，一个小时是正常的。训练时间长是因为本项目使用了未经优化的harvard-transformer，仅供大家理解transformer和NMT项目使用。如果想缩短训练时间或者开发更为实用的翻译项目，建议使用优化程度更高的fairseq～

**Comment by tan-yishu** [comment]
> 训练时间在readme和知乎文章中已经说明了哦，一个小时是正常的。训练时间长是因为本项目使用了未经优化的harvard-transformer，仅供大家理解transformer和NMT项目使用。如果想缩短训练时间或者开发更为实用的翻译项目，建议使用优化程度更高的fairseq～

谢谢~
